export const HIDE_LOADER = 'APP/HIDE_LOADER';
export const SHOW_LOADER = 'APP/SHOW_LOADER';

export const FETCH_GROUP = 'GROUP/FETCH_GROUP';

export const FETCH_NEWS = 'NEWS/FETCH_NEWS';
export const FETCH_POST = 'NEWS/FETCH_POST';
export const SET_CURRENT_PAGE = 'NEWS/SET_CURRENT_PAGE';
export const SET_CURRENTS_POSTS_ON_PAGE = 'NEWS/SET_CURRENTS_POSTS_ON_PAGE';